export const theme = {
  colors: {
    primary: "#13B2A9",
    primaryDark: "#0F8C84",
    accent: "#2C3E50",
    background: "#FFFFFF",
    surface: "#F8F8F8",
    card: "#FFFFFF",
    textPrimary: "#2C3E50",
    textSecondary: "#7F8C8D",
    textTertiary: "#95A5A6",
    border: "#E0E0E0",
    divider: "#F0F0F0",
    success: "#13B2A9",
    error: "#FF5252",
    warning: "#FFC107",
    info: "#2196F3",
    onPrimary: "#FFFFFF",
    onAccent: "#FFFFFF",
    onSurface: "#2C3E50",
    onBackground: "#2C3E50",
    inputBackground: "#F7F7F7",
    placeholder: "#BDC3C7"
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    round: 9999,
  },
  typography: {
    h1: { fontSize: 32, fontWeight: "700" as const },
    h2: { fontSize: 24, fontWeight: "600" as const },
    h3: { fontSize: 20, fontWeight: "600" as const },
    body: { fontSize: 16, fontWeight: "400" as const },
    caption: { fontSize: 14, fontWeight: "400" as const },
    small: { fontSize: 12, fontWeight: "400" as const },
  },
  shadows: {
    sm: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
    },
    md: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 4,
    },
    lg: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 8,
      elevation: 8,
    },
  },
};